#### Understanding the basics of NumPy

In [1]:
import numpy as np

In [3]:
# OD Vector ->
arr=np.array(42)
print(arr)

# 1D array ->
array_1d=np.array([1,2,3,4,5])
print(f"1D array is : {array_1d}")

# 2D array ->
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(f"2D array is : \n{array_2d}")

42
1D array is : [1 2 3 4 5]
2D array is : 
[[1 2 3 4]
 [5 6 7 8]]


#### List vs NumPy array 

In [4]:
python_list=[1,2,3,4,5]
print(f"Python list multiplication : {python_list*2}")

np_array=np.array([1,2,3,4,5])
print(f"Np array multiplication: {np_array*2}")

Python list multiplication : [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Np array multiplication: [ 2  4  6  8 10]


Comparing time taken by normal multiplication and numpy multiplication

In [5]:
import time

start=time.time()
python_list=[i*2 for i in range(1000000)]
print(f"Python list multiplication time taken  : {time.time()-start}")


start=time.time()
np_array=np.arange(1000000)*2
print(f"Numpy  multiplication time taken  : {time.time()-start}")


Python list multiplication time taken  : 0.07148218154907227
Numpy  multiplication time taken  : 0.014467716217041016


##### Creating array from scratch in NumPy

In [6]:
#using the zeros and ones method allows us to create arrays with all values equal to either 0/1
zeros=np.zeros((3,4))
print("zeroes array :\n",zeros)

ones=np.ones((2,3))
print("ones array :\n",ones)

# creating array of constant values -> 

full=np.full((2,2),7)
print("constant array :\n",full)


# creating a array of random values -> 

random=np.random.random((2,3))
print("random array :\n",random)

#creating a sequence 
# range -> non inclusive outer boundary
sequence=np.arange(start=0,step=2,stop=10)
print("sequence array :\n",sequence)

zeroes array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :
 [[1. 1. 1.]
 [1. 1. 1.]]
constant array :
 [[7 7]
 [7 7]]
random array :
 [[0.72423469 0.86863502 0.00778229]
 [0.94936782 0.17219676 0.07777161]]
sequence array :
 [0 2 4 6 8]


#### Array Properties

In [7]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(f"Shape of array is : {arr.shape}")
print(f"Size of array is : {arr.size}")
print(f"Dimension of array is : {arr.ndim}")
print(f"Data type of array is : {arr.dtype}")

#even if 1 element of the array is float, then the data type is shown as float

Shape of array is : (2, 3)
Size of array is : 6
Dimension of array is : 2
Data type of array is : int64


Array reshaping operations

In [8]:
arr=np.arange(12)
print(f"Original array is : {arr}")

reshaped=arr.reshape((3,4))
print(f"Reshaped array is :\n {reshaped}")

flattened=reshaped.flatten()
print(f"Flattened array is :\n {flattened}")

raveled=reshaped.ravel()
print(f"Raveled array is :\n {raveled}")

# the main difference between raveled and flattened is that raveled makes changes in the original array while the raveled returns a copy of the flattened


# Finding transpose of matrix -> 

transpose=reshaped.T
print(f"The transpose array is : \n {transpose}")


Original array is : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array is :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
The transpose array is : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### Vectors, Matrix and Tensors in NumPy

In [9]:
vector=np.array([1,2,3,4,5])
print(" Vector :\n",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix :\n",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor is  :\n",tensor)


 Vector :
 [1 2 3 4 5]
Matrix :
 [[1 2 3]
 [4 5 6]]
Tensor is  :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
