### Numpy array operations

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(f"Basic slicing : {arr[2:7]}")
print(f"Slicing with step : {arr[1:8:2]}")
print(f"Negative indexing : {arr[-3]}")


[ 1  2  3  4  5  6  7  8  9 10]
Basic slicing : [3 4 5 6 7]
Slicing with step : [2 4 6 8]
Negative indexing : 8


In [3]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f"Specific element : {arr_2d[1,2]}") # prints the 2nd element(index) in the 1st row
print(f"Entire row : {arr_2d[1]}")
print(f"Specific column of all rows : {arr_2d[:,1]}")

Specific element : 6
Entire row : [4 5 6]
Specific column of all rows : [2 5 8]


Sorting in 1D and 2D arrays

In [4]:
#sorting 1D arrays in numpy
unsorted=np.array([1,4,6,3,2,9,3,1,5,8,7,4])
print(f"Sorted array is {np.sort(unsorted)}")

#Sorting 2D arrays in numpy 

unsorted_2d=np.array([[3,1],[1,2],[2,3]])
print(f"Sorted 2D array by column : {np.sort(unsorted_2d,axis=0)}")
print(f"Sorted 2D array by row : {np.sort(unsorted_2d,axis=1)}")

# column wise sorting is mostly used - top down sorting takes place

Sorted array is [1 1 2 3 3 4 4 5 6 7 8 9]
Sorted 2D array by column : [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row : [[1 3]
 [1 2]
 [2 3]]


Filtering operations in arrays

In [5]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print(f"Even numbers are : {even_numbers}")

Even numbers are : [ 2  4  6  8 10]


Filtering operations with mask

In [6]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
mask=numbers>5
print(mask)
print(f"Numbers greater than 5 are : {numbers[mask]}")

[False False False False False  True  True  True  True  True]
Numbers greater than 5 are : [ 6  7  8  9 10]


Fancy indexing vs np.where() clause

In [7]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print(f"Values obtained from NP where are : {numbers[where_result]}") #somewhat similar to masking

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Values obtained from NP where are : [ 6  7  8  9 10]


In [8]:
# 'numbers' has to be an np array for where operation to take place. the 3 arguments are -> 1. condition 2. element if condition is true 3. element manipulation if condition is false
condition_array=np.where(numbers>5,numbers*2,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [9]:
condition_array=np.where(numbers>5,"true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [10]:
condition_array=np.where(numbers>5,True,False)
print(condition_array)

[False False False False False  True  True  True  True  True]


Adding and joining of arrays

In [11]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

# in this process , the two arrays do not get added, instead the sum of the corresponding individual elements is printed out
combined=arr1+arr2
print(combined)

[5 7 9]


In [12]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


Compatibility Check in arrays

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

d=np.array([7,8,9,10,11])


print(f"Compatibility shape check -> {a.shape==b.shape}")
print(f"Compatibility shape check -> {a.shape==d.shape}")

Compatibility shape check -> True
Compatibility shape check -> False


In [14]:
original=np.array([[1,2],[3,4]])
new_row=np.array([5,6])

with_new_row=np.vstack((original,new_row))
print(with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


Delete operations in Arrays

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
deleted=np.delete(arr,2)
print(f"Array after deletion is : {deleted}")

Array after deletion is : [ 1  2  4  5  6  7  8  9 10]
