### Vector Operations in NumPy

In [1]:
import numpy as np

In [2]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])

#Vector addition -> 
print(f"Vector addition : {vector1+vector2}")


#Vector multiplication ->
print(f"Vector multiplication : {vector1*vector2}")

# Dot product in vectors ->
print(f"Vector dot product is {np.dot(vector1,vector2)}")


#Finding the angle between two vectors -> 
angle=np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print(f"The angle between the two vectors is : {angle}")



Vector addition : [ 7  9 11 13 15]
Vector multiplication : [ 6 14 24 36 50]
Vector dot product is 130
The angle between the two vectors is : 0.26554161733900966


##### Vectorized Operations

In [3]:
# the operations that are performed individually on each element of the array
restaurant_types=np.array(['cafe','chat point','chinese','pizza','fine dine'])

vectorized_upper=np.vectorize(str.upper)#vectorising normal python method
print(f"Vectorized upper : {vectorized_upper(restaurant_types)}")

Vectorized upper : ['CAFE' 'CHAT POINT' 'CHINESE' 'PIZZA' 'FINE DINE']


In [4]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Kapoor's Cafe
    [2, 120000, 140000, 160000, 190000],  # SLV Coffee Bar
    [3, 200000, 230000, 260000, 300000],  # Kedia's fun food
    [4, 180000, 210000, 240000, 270000],  # Corner House
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

Broadcast Operations on Sales Data

In [5]:
# calculating average sales per month
monthly_average=sales_data[:,1:]/12
print(monthly_average)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
