## Practice Questions on NumPy

In [1]:
import numpy as np

### Check Valid Sudoku  

In [2]:
sudoku= np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
np.sum(sudoku,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [4]:
np.sum(sudoku,axis=0)


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
valid=False
rows=np.sum(sudoku,axis=0)
columns=np.sum(sudoku,axis=0)
for row_sum in rows:
    if row_sum!=45:
        break
else:
    valid=True
    
for column_sum in columns:
    if column_sum!=45:
        break
else:
    valid=True
    
if valid:
    print("Sudoku is valid")
else:
    print("Sudoku is invalid")
    


Sudoku is valid


In [6]:
sudoku[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [7]:
sudoku[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [8]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(sudoku[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [9]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=sudoku[i:i+3,j:j+3]
        if n.sum()!=45:
            break
    valid=True


### Analysis on Student Data

In [10]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [11]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [12]:
#Find the average age of students.
average_age=data[:,0].mean()
print(average_age)

18.4


In [13]:
#Extract Math marks of all students.
math_marks=data[:,1]
print(math_marks)

[85 92 76 65 90]


In [14]:
#Find the highest Science mark.
science_highest=data[:,2].max()
print(science_highest)

95


In [15]:
#Get details of the student who scored more than 90 in Math.
condition=data[:,1]>90
data[condition]

array([[19, 92, 88]])

In [16]:
#Increase Math marks of all students by 5.
data[:,1]+10

array([ 95, 102,  86,  75, 100])

In [17]:
#Find how many students are younger than 19.
data[data[:,0]<19]
no_of_students=np.sum(data[:,0]<19)
print(no_of_students)

3


In [18]:
#Calculate the average marks in each subject (column-wise mean).
average_marks=np.mean(data[:,1:],axis=0)
average_marks

array([81.6, 83.2])

In [19]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80)&(data[:,2]>=80)]


array([[19, 92, 88],
       [20, 90, 85]])

In [20]:
data[:,2]

array([78, 88, 95, 70, 85])

In [21]:
#Replace all Science marks < 75 with 0.
marks=data[:,2]<75
marks



array([False, False, False,  True, False])

In [22]:
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])